name: movie_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.3+1
  flutter_loggy_dio: ^3.1.0
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  form_builder_validators: ^11.1.2
  go_router: ^14.8.1
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  mocktail: ^1.0.4
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  q_architecture: ^1.0.5
  retrofit: ^4.4.2
  sembast: ^3.8.4
  sentry_flutter: ^8.11.0
  shared_preferences: ^2.5.3

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0E1324"
  image: assets/images/q_logo.png

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_flavorizr: ^2.3.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  

  assets:
    - assets/images/
    - assets/icons/
